POST http://127.0.0.1:8000/login
Content-Type: application/json

# {"username": "spencer", "password": "test123"}
{"username": "reddy", "password": "test123"}

###
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "spencer3", "password": "test123", "role": "E"}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json