# Generated by Django 4.2.5 on 2023-09-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_task_actual_end_time_task_actual_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
