# Generated by Django 4.2.5 on 2023-09-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('actual_start_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField()),
                ('in_progress', models.BooleanField(verbose_name=False)),
                ('is_complete', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
